Single video page
Ankur9669/FitVid-React pull request #9
Opened 2022-04-04 20:24 UTC by Ankur9669

Files to check:
1. SinglePage.js
2. LeftContainer.js
3. RightContainer.js
4. leftcontainer.css
5. rightcontainer.css

![image](https://user-images.githubusercontent.com/65125998/161625981-a630a3a1-e77d-4340-9746-3e765356a88f.png)

2022-04-05 05:09 UTC, Naman-Saxena1 requested changes
Code looks great 👍 
I do have 2 nit picks for UI design
### 1. Alignment should be same for consistent design, both should start from same height
### 2. On hover of options, it should be cursor: pointer to indicate it is clickable
![InkedCapture3_LI](https://user-images.githubusercontent.com/90456667/161683041-17a8fc6b-ef03-42b8-992b-823a4e5c8a60.jpg)

2022-04-05 05:09 UTC, Naman-Saxena1 commented on FitVid/src/Pages/SingleVideoPage/LeftContainer/leftcontainer.css
> +   /* min-height: 120vh; */
If not using, can remove commented

2022-04-05 07:50 UTC, Ankur9669 commented on FitVid/src/Pages/SingleVideoPage/LeftContainer/leftcontainer.css
> +   /* min-height: 120vh; */
Done

2022-04-06 08:05 UTC, Priya-Patel31 approved these changes
The code looks good . Could'nt find anything to suggest . You can go ahead merge .

2022-04-06 18:23 UTC, merged